version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: nestmart-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "sqladmin123!"
      MSSQL_PID: Express
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-sqlserver.sql:/docker-entrypoint-initdb.d/init-sqlserver.sql
      - ./nestmart.sql:/docker-entrypoint-initdb.d/nestmart.sql
    networks:
      - nestmart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'sqladmin123!' -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # NestMart Application
  nestmart-app:
    build: .
    container_name: nestmart-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_NAME=nestmart
    depends_on:
      - sqlserver
    networks:
      - nestmart-network
    restart: unless-stopped
    volumes:
      - ./web/assets/admin/images/uploads:/usr/local/tomcat/webapps/nestmart/assets/admin/images/uploads

volumes:
  sqlserver_data:

networks:
  nestmart-network:
    driver: bridge
